stages:
  - build
  - test
  - build-artifact

build-windows-master:
  stage: build
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - echo "Building Windows Master"
    - Set-Variable -Name "buildpath" -Value (($pwd).path + "\build")
    - mkdir -P $buildpath
    - cd $buildpath
    - echo "Init project in:"+($pwd).path
    - C:\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -DCMAKE_BUILD_TYPE=RELEASE -G Ninja $buildpath\..
    - echo "Starting build in:" + ($buildpath).path
    - C:\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build $buildpath --config Release -- -j 4
    - Set-Variable -Name "DATE" -Value (Get-Date -Format "yyyy_MM_dd")
    - Set-Variable -Name "FNAME" -Value ("\master\" + $DATE + "_" + $env:CI_COMMIT_REF_NAME + "_" + $env:CI_PIPELINE_ID)
    - Set-Variable -Name "outputpath" -Value ($buildpath + "\bin\win\release")
    - echo $FNAME
    - New-Item -Path "C:\MOLFLOW_CI" -Name $FNAME -ItemType "directory" -Force
    - Copy-Item ($outputpath + "\*") -Destination C:\MOLFLOW_CI\$FNAME\ -Recurse -Force
  after_script:
    - echo "Finished"
  tags:
    - windows

build-debian-master:
  stage: build
  before_script:
    - whoami
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - echo "Building Debian Master"
    - buildpath=$(pwd)"/build"
    - mkdir -p $buildpath
    - cd $buildpath
    - echo "Init project in:" $(pwd)
    - cmake -DCMAKE_BUILD_TYPE=RELEASE $buildpath/..
    - echo "Starting build in:" $buildpath
    - cmake --build $buildpath --config Release -- -j 4
    - export DATE=`date +%Y_%m_%d`
    - export FNAME=master'/'$DATE'_'$CI_COMMIT_REF_NAME'_'$CI_PIPELINE_ID
    - export outputpath=$buildpath"/bin/linux_debian/release"
    - echo $FNAME
    - mkdir -p ~/MOLFLOW_CI'/'$FNAME
    - cp -r $outputpath/* ~/MOLFLOW_CI'/'$FNAME'/'
    - ls ~/
    - ls ~/MOLFLOW_CI'/'
    - ls ~/MOLFLOW_CI'/'$FNAME'/'
  after_script:
    - echo "Finished"
  tags:
    - debian

build-fedora-master:
  stage: build
  before_script:
    - whoami
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - echo "Building Fedora Master"
    - neofetch
    - buildpath=$(pwd)"/build"
    - mkdir -p $buildpath
    - cd $buildpath
    - echo "Init project in:" $(pwd)
    - cmake -DCMAKE_BUILD_TYPE=RELEASE $buildpath/..
    - echo "Starting build in:" $buildpath
    - cmake --build $buildpath --config Release -- -j 4
    - export DATE=`date +%Y_%m_%d`
    - export FNAME=master'/'$DATE'_'$CI_COMMIT_REF_NAME'_'$CI_PIPELINE_ID
    - export outputpath=$buildpath"/bin/linux_debian/release"
    - echo $FNAME
    - mkdir -p ~/MOLFLOW_CI'/'$FNAME
    - cp -r $outputpath/* ~/MOLFLOW_CI'/'$FNAME'/'
    - ls ~/
    - ls ~/MOLFLOW_CI'/'
    - ls ~/MOLFLOW_CI'/'$FNAME'/'
  after_script:
    - echo "Finished"
  tags:
    - fedora

test-debian:
  stage: test
  before_script:
    - whoami
  script:
    - echo "Testing Debian Master"
    - export DATE=`date +%Y_%m_%d`
    - export FNAME=master'/'$DATE'_'$CI_COMMIT_REF_NAME'_'$CI_PIPELINE_ID
    - cd ~/MOLFLOW_CI'/'$FNAME'/'
    - ./testsuit --gtest_output="xml:report.xml"
  after_script:
    - echo "Finished"
  artifacts:
    when: always
    reports:
      junit: report.xml
  tags:
    - debian

test-fedora:
  stage: test
  before_script:
    - whoami
  script:
    - echo "Testing Fedora Master"
    - export DATE=`date +%Y_%m_%d`
    - export FNAME=master'/'$DATE'_'$CI_COMMIT_REF_NAME'_'$CI_PIPELINE_ID
    - cd ~/MOLFLOW_CI'/'$FNAME'/'
    - ./testsuit --gtest_output="xml:report.xml"
  after_script:
    - echo "Finished"
  artifacts:
    when: always
    reports:
      junit: report.xml
  tags:
    - fedora

test-windows:
  stage: test
  before_script:
    - whoami
  script:
    - Write-Host "Testing Windows Master"
    - Set-Variable -Name "DATE" -Value (Get-Date -Format "yyyy_MM_dd")
    - Set-Variable -Name "FNAME" -Value ("\master\" + $DATE + "_" + $env:CI_COMMIT_REF_NAME + "_" + $env:CI_PIPELINE_ID)
    - Write-Host $FNAME
    - Set-Location C:\MOLFLOW_CI\$FNAME\
    - pwd
    - ls C:\MOLFLOW_CI\$FNAME\
    - $AllArgs = @("--gtest_output='xml:report.xml'")
    - powershell.exe -c "./testsuit.exe $AllArgs"
  after_script:
    - Write-Host "Finished"
  artifacts:
    when: always
    reports:
      junit: report.xml
  tags:
    - windows

build-artifact-windows-master:
  stage: build-artifact
  script:
    - Set-Variable -Name "DATE" -Value (Get-Date -Format "yyyy_MM_dd")
    - Set-Variable -Name "FNAME" -Value ("\master\" + $DATE + "_" + $env:CI_COMMIT_REF_NAME + "_" + $env:CI_PIPELINE_ID)
    - Write-Host $FNAME
    - Compress-Archive -Path C:\MOLFLOW_CI\$FNAME\ -DestinationPath .\molflow_windows.zip
  artifacts:
    paths:
      - .\molflow_windows.zip
    expire_in: 54 weeks
  tags:
    - windows
  only:
    - master

build-artifact-debian-master:
  stage: build-artifact
  script:
    - export DATE=`date +%Y_%m_%d`
    - export FNAME=master'/'$DATE'_'$CI_COMMIT_REF_NAME'_'$CI_PIPELINE_ID
    - echo $FNAME
    - 7za a ./molflow_debian.zip ~/MOLFLOW_CI'/'$FNAME'/'
  artifacts:
    paths:
      - ./molflow_debian.zip
    expire_in: 54 weeks
  tags:
    - debian
  only:
    - master

build-artifact-fedora-master:
  stage: build-artifact
  script:
    - export DATE=`date +%Y_%m_%d`
    - export FNAME=master'/'$DATE'_'$CI_COMMIT_REF_NAME'_'$CI_PIPELINE_ID
    - echo $FNAME
    - 7za a ./molflow_fedora.zip ~/MOLFLOW_CI'/'$FNAME'/'
  artifacts:
    paths:
      - ./molflow_fedora.zip
    expire_in: 54 weeks
  tags:
    - fedora
  only:
    - master

build-artifact-windows-branch:
  stage: build-artifact
  script:
    - Set-Variable -Name "DATE" -Value (Get-Date -Format "yyyy_MM_dd")
    - Set-Variable -Name "FNAME" -Value ("\master\" + $DATE + "_" + $env:CI_COMMIT_REF_NAME + "_" + $env:CI_PIPELINE_ID)
    - echo $FNAME
    - Compress-Archive -Path C:\MOLFLOW_CI\$FNAME\ -DestinationPath .\molflow_windows.zip
  artifacts:
    paths:
      - .\molflow_windows.zip
    expire_in: 4 weeks
  tags:
    - windows
  only:
    - branches
  except:
    - master
    - tags

build-artifact-debian-branch:
  stage: build-artifact
  script:
    - export DATE=`date +%Y_%m_%d`
    - export FNAME=master'/'$DATE'_'$CI_COMMIT_REF_NAME'_'$CI_PIPELINE_ID
    - echo $FNAME
    - 7za a ./molflow_debian.zip ~/MOLFLOW_CI'/'$FNAME'/'
  artifacts:
    paths:
      - ./molflow_debian.zip
    expire_in: 4 weeks
  tags:
    - debian
  only:
    - branches
  except:
    - master
    - tags
  
build-artifact-fedora-branch:
  stage: build-artifact
  script:
    - export DATE=`date +%Y_%m_%d`
    - export FNAME=master'/'$DATE'_'$CI_COMMIT_REF_NAME'_'$CI_PIPELINE_ID
    - echo $FNAME
    - 7za a ./molflow_fedora.zip ~/MOLFLOW_CI'/'$FNAME'/'
  artifacts:
    paths:
      - ./molflow_fedora.zip
    expire_in: 4 weeks
  tags:
    - fedora
  only:
    - branches
  except:
    - master
    - tags
